version: '3.8'

services:
  web:
    ports: #ポートを公開する(ホスト:コンテナ)
      # - '8000:80' #8000でアクセスされたら、80を使用する
      - '8080:8080'
    build: ./docker/apache/ #Dockerfileが存在するディレクトリの相対パス
    volumes: #コンテナと共有したいパスを指定
      - ./logs :/usr/local/apache2/logs/httpd/ # コンテナに入らず、apacheのlogを見るためマウント
    depends_on: # Service同士の依存関係を指定
      - ui #`docker-compose run`した際にapacheより前にuiコンテナが実行される
    links: #他のコンテナに接続する(コンテナのhostsに追加される)
      - ui
  ui:
    build: 
      context: ./
      dockerfile: ./docker/ui/Dockerfile
    volumes:
      - ./nuxt :/app
    depends_on:
      - api
    links:
      - api
  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./laravel :/var/www/html
    depends_on:
      - db
      - mailhog
    links:
      - db
  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
      - ./logs :/var/log/mysql
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db-store: